apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - "user.openshift.io"
  resources:
  - groups
  verbs:
  - get
  - create
  - patch
