---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sis-ns-manager-github-webhook-secret
  namespace: sis-ns-manager
spec:
  encryptedData:
    WebHookSecretKey: AgBpndoVHMyOGVFpc66UfC+v70470WVyWI0mMfnougED0v7H2Ukhv8K8XBr3ODudO4QgUpzdpqtjiC+oe6n1wYoOPx5gPlA81r0CnX0K2UhsD9s/GfvA8PYLxdqtfup4g+V5f5JwuKwH9k13g6hotfrFvnoBk4ffUvUo8pI+pCVevX681WUn21mNPohpWZrKPmbgYrgX7sCO9I50xQYlCA18BnQpJ2x77swHZYAlITwEczZxxD0bb08J9tqt0PWXKzvvxZOx8gUUQ+nEC/kiE/NHIMg1H6Xzgtm1DyvD7IJxQ3vA1db+m+UkaVr+HfQJQz4sXPsXvKOA11JY4rOhUWLo1XRJ5mzWfep2PiEV6qMysEjwjW8LUghxqIvBkJESVVQL9QhjKJpK9bBHqybieuuIdC73UyfsG60Ne+PE3NXe/DYfU75YlNJA/eCbgoIpI9o8+3ffHQ33qm97oETXJr/nU+A6u1eNfkgcAcHvGPcd2jwjmwSk0SN6AAbBC2VepXOhuucs0CVQxj1MZkGyhnsTJw7FKbdUiyODDGcWadPF8Nmhmuy+X5+YkeyJAPVOJXChLnGJ/bbgtQRubDVD/M159+mM9Amxuw56Of05ufMVD6G519lgwheOOlxoPKYBoxRskthpFgXX3dkUjHb8yD9FcLGkMddN+k5yUw6hqfCLdZTJrkD5xKRP47ZdHec+x7yCGmdeveevcPVKLvwOR6BzEKRYB1rI1nU6yFVSEwSbYtKaXcg=
  template:
    metadata:
      creationTimestamp: null
      name: sis-ns-manager-github-webhook-secret
      namespace: sis-ns-manager
    type: Opaque