apiVersion: apps/v1
kind: Deployment
metadata:
  name: sis-ns-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sis-ns-manager
  template:
    metadata:
      labels:
        app: sis-ns-manager
    spec:
      serviceAccountName: manager
      containers:
        - name: sis-ns-manager
          image: image-registry.openshift-image-registry.svc:5000/sis-ns-manager/sis-ns-manager
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
