apiVersion: apps/v1
kind: Deployment
metadata:
  name: sis-ns-manager
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"sis-ns-manager:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"sis-ns-manager\")].image","paused":"false"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sis-ns-manager
  template:
    metadata:
      labels:
        app: sis-ns-manager
    spec:
      serviceAccountName: sis-ns-manager
      containers:
        - name: sis-ns-manager
          image: sis-ns-manager:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
