apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - build.yaml
  - pruner-build.yaml
  - pruner-cronjob.yaml
  - pruner-serviceaccount.yaml
  - serviceaccount.yaml
  - namespace.yaml
  - deployment.yaml
  - redis.yaml
  - route.yaml
  - service.yaml
  - sis-ns-manager.clusterrole.yaml
  - sis-ns-manager.clusterrolebinding.yaml
