apiVersion: v1
kind: ServiceAccount
metadata:
  name: manager
  namespace: sis-ns-manager
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-clusterrole
subjects:
- kind: ServiceAccount
  name: manager
  namespace: sis-ns-manager
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-clusterrole
rules:
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - user.openshift.io
  resources:
  - users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get