apiVersion: batch/v1
kind: CronJob
metadata:
  name: sis-ns-manager-sidecar
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"sis-ns-manager-sidecar:latest","namespace":"sis-ns-manager"},"fieldPath":"spec.jobTemplate.spec.template.spec.containers[?(@.name==\"sis-ns-manager-sidecar\")].image"}]'
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: sis-ns-manager-sidecar
        spec:
          serviceAccountName: sidecar
          restartPolicy: Never
          containers:
            - name: sis-ns-manager-sidecar
              image: image-registry.openshift-image-registry.svc:5000/sis-ns-manager/sis-ns-manager-sidecar
