apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sis-ns-manager
rules:
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - create
      - delete
      - patch
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
    verbs:
      - create
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - patch
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - delete
      - update
      - patch