name: okd-cs-test-0 local runner test
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: runner-scaleset
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
